import { Transaction, Account } from '@/shared/types/shared';
import { AccountCardDTO, accountToCardDTO } from '@/shared/types/accounts';

export type { Transaction, Account } from '@/shared/types/shared';

// CC: Enhanced mock data with ≥20 accounts for Smart Accounts Deck requirements
export const mockAccountsEnhanced = [
  {
    id: 'acc_001',
    familyId: 'demo_family',
    name: 'Main Checking',
    accountType: 'depository' as const,
    accountSubtype: 'checking' as const,
    institutionName: 'Chase Bank',
    balance: 12450.0,
    availableBalance: 11200.0,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****1234',
      apy: 0.01,
      fees: [],
      sparklineData: [12200, 12300, 12100, 12400, 12450],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_002',
    familyId: 'demo_family',
    name: 'Emergency Fund',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'Bank of America',
    balance: 25780.5,
    availableBalance: 25780.5,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****5678',
      apy: 2.15,
      fees: [],
      sparklineData: [25200, 25400, 25600, 25700, 25780],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_003',
    familyId: 'demo_family',
    name: 'Rewards Card',
    accountType: 'credit' as const,
    accountSubtype: 'credit_card' as const,
    institutionName: 'Wells Fargo',
    balance: -1245.3,
    availableBalance: 8754.7,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****9012',
      creditLimit: 10000,
      fees: [],
      sparklineData: [-1100, -1200, -1300, -1200, -1245],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_004',
    familyId: 'demo_family',
    name: 'Investment Portfolio',
    accountType: 'investment' as const,
    accountSubtype: 'brokerage' as const,
    institutionName: 'Schwab',
    balance: 45600.25,
    availableBalance: 45600.25,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****3456',
      fees: [],
      sparklineData: [44800, 45200, 45100, 45400, 45600],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // CC: Additional 20 accounts for Smart Accounts Deck virtual scrolling
  {
    id: 'acc_005',
    familyId: 'demo_family',
    name: 'Business Checking',
    accountType: 'depository' as const,
    accountSubtype: 'checking' as const,
    institutionName: 'JPMorgan Chase',
    balance: 8920.14,
    availableBalance: 8920.14,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****7890',
      apy: 0.05,
      fees: [],
      sparklineData: [8800, 8850, 8900, 8880, 8920],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_006',
    familyId: 'demo_family',
    name: '401(k) Retirement',
    accountType: 'investment' as const,
    accountSubtype: '401k' as const,
    institutionName: 'Fidelity',
    balance: 174250.67,
    availableBalance: 174250.67,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****4567',
      fees: [],
      sparklineData: [172000, 173000, 173500, 174000, 174250],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_007',
    familyId: 'demo_family',
    name: 'Traditional IRA',
    accountType: 'investment' as const,
    accountSubtype: 'ira' as const,
    institutionName: 'Vanguard',
    balance: 62340.22,
    availableBalance: 62340.22,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****8901',
      fees: [],
      sparklineData: [61800, 62000, 62100, 62200, 62340],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_008',
    familyId: 'demo_family',
    name: 'Health Savings',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'HSA Bank',
    balance: 12450.11,
    availableBalance: 12450.11,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****2345',
      apy: 1.75,
      fees: [],
      sparklineData: [12200, 12300, 12350, 12400, 12450],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_009',
    familyId: 'demo_family',
    name: 'College 529 Plan',
    accountType: 'investment' as const,
    accountSubtype: '529' as const,
    institutionName: 'T. Rowe Price',
    balance: 18230.89,
    availableBalance: 18230.89,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****6789',
      fees: [],
      sparklineData: [17800, 18000, 18100, 18150, 18230],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_010',
    familyId: 'demo_family',
    name: 'Emergency Savings',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'Ally Bank',
    balance: 8500.0,
    availableBalance: 8500.0,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****0123',
      apy: 4.25,
      fees: [],
      sparklineData: [8200, 8300, 8400, 8450, 8500],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_011',
    familyId: 'demo_family',
    name: 'Travel Rewards',
    accountType: 'credit' as const,
    accountSubtype: 'credit_card' as const,
    institutionName: 'American Express',
    balance: -2890.45,
    availableBalance: 7109.55,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****4567',
      creditLimit: 10000,
      fees: [],
      sparklineData: [-2500, -2700, -2800, -2850, -2890],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_012',
    familyId: 'demo_family',
    name: 'Business Savings',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'Capital One',
    balance: 34567.89,
    availableBalance: 34567.89,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****8901',
      apy: 3.5,
      fees: [],
      sparklineData: [34000, 34200, 34400, 34500, 34567],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_013',
    familyId: 'demo_family',
    name: 'Roth IRA',
    accountType: 'investment' as const,
    accountSubtype: 'roth_ira' as const,
    institutionName: 'E*TRADE',
    balance: 56789.12,
    availableBalance: 56789.12,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****2345',
      fees: [],
      sparklineData: [56200, 56400, 56600, 56700, 56789],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_014',
    familyId: 'demo_family',
    name: 'Cash Management',
    accountType: 'depository' as const,
    accountSubtype: 'checking' as const,
    institutionName: 'Goldman Sachs',
    balance: 15678.9,
    availableBalance: 15678.9,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****6789',
      apy: 2.75,
      fees: [],
      sparklineData: [15400, 15500, 15600, 15650, 15678],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_015',
    familyId: 'demo_family',
    name: 'Cashback Card',
    accountType: 'credit' as const,
    accountSubtype: 'credit_card' as const,
    institutionName: 'Discover',
    balance: -567.23,
    availableBalance: 9432.77,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****0123',
      creditLimit: 10000,
      fees: [],
      sparklineData: [-400, -500, -550, -560, -567],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_016',
    familyId: 'demo_family',
    name: 'Money Market',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'Marcus by Goldman Sachs',
    balance: 67890.34,
    availableBalance: 67890.34,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****4567',
      apy: 4.1,
      fees: [],
      sparklineData: [67200, 67500, 67700, 67800, 67890],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_017',
    familyId: 'demo_family',
    name: 'Crypto Portfolio',
    accountType: 'investment' as const,
    accountSubtype: 'brokerage' as const,
    institutionName: 'Coinbase',
    balance: 12345.67,
    availableBalance: 12345.67,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****8901',
      fees: [],
      sparklineData: [11000, 11500, 12000, 12200, 12345],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_018',
    familyId: 'demo_family',
    name: 'Student Loan',
    accountType: 'loan' as const,
    accountSubtype: 'student' as const,
    institutionName: 'Navient',
    balance: -23456.78,
    availableBalance: 0,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****2345',
      fees: [],
      sparklineData: [-24000, -23800, -23600, -23500, -23456],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_019',
    familyId: 'demo_family',
    name: 'Auto Loan',
    accountType: 'loan' as const,
    accountSubtype: 'auto' as const,
    institutionName: 'Chase Auto Finance',
    balance: -18765.43,
    availableBalance: 0,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****6789',
      fees: [],
      sparklineData: [-19500, -19200, -19000, -18800, -18765],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_020',
    familyId: 'demo_family',
    name: 'Home Equity LOC',
    accountType: 'credit' as const,
    accountSubtype: 'line_of_credit' as const,
    institutionName: 'Wells Fargo',
    balance: -5432.1,
    availableBalance: 44567.9,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****0123',
      creditLimit: 50000,
      fees: [],
      sparklineData: [-5000, -5200, -5300, -5400, -5432],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_021',
    familyId: 'demo_family',
    name: 'CD Ladder 1',
    accountType: 'depository' as const,
    accountSubtype: 'cd' as const,
    institutionName: 'Navy Federal',
    balance: 25000.0,
    availableBalance: 0,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****4567',
      apy: 4.75,
      fees: [],
      sparklineData: [24800, 24900, 24950, 24975, 25000],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_022',
    familyId: 'demo_family',
    name: 'Brokerage Account',
    accountType: 'investment' as const,
    accountSubtype: 'brokerage' as const,
    institutionName: 'TD Ameritrade',
    balance: 89012.34,
    availableBalance: 89012.34,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****8901',
      fees: [],
      sparklineData: [87000, 88000, 88500, 88800, 89012],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_023',
    familyId: 'demo_family',
    name: 'Joint Savings',
    accountType: 'depository' as const,
    accountSubtype: 'savings' as const,
    institutionName: 'USAA',
    balance: 43210.98,
    availableBalance: 43210.98,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****2345',
      apy: 3.25,
      fees: [],
      sparklineData: [42800, 43000, 43100, 43150, 43210],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'acc_024',
    familyId: 'demo_family',
    name: 'Premium Card',
    accountType: 'credit' as const,
    accountSubtype: 'credit_card' as const,
    institutionName: 'Chase Sapphire',
    balance: -4567.89,
    availableBalance: 20432.11,
    currency: 'USD',
    isActive: true,
    isManual: false,
    syncStatus: 'active' as const,
    metadata: {
      accountNumber: '****6789',
      creditLimit: 25000,
      fees: [],
      sparklineData: [-4200, -4300, -4400, -4500, -4567],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// CC: Enhanced institution data with logos and branding for Smart Accounts Deck
export const mockInstitutions = {
  'Chase Bank': {
    name: 'Chase Bank',
    color: '#117A65',
    logo: '/institution-logos/chase.png',
  },
  'Bank of America': {
    name: 'Bank of America',
    color: '#E51B23',
    logo: '/institution-logos/boa.png',
  },
  'Wells Fargo': {
    name: 'Wells Fargo',
    color: '#D71E2B',
    logo: '/institution-logos/wells-fargo.png',
  },
  Schwab: {
    name: 'Charles Schwab',
    color: '#00A0DF',
    logo: '/institution-logos/schwab.png',
  },
  'JPMorgan Chase': {
    name: 'JPMorgan Chase',
    color: '#117A65',
    logo: '/institution-logos/chase.png',
  },
  Fidelity: {
    name: 'Fidelity',
    color: '#00653A',
    logo: '/institution-logos/fidelity.png',
  },
  Vanguard: {
    name: 'Vanguard',
    color: '#B41E3B',
    logo: '/institution-logos/vanguard.png',
  },
  'HSA Bank': {
    name: 'HSA Bank',
    color: '#4A90E2',
    logo: '/institution-logos/hsa-bank.png',
  },
  'T. Rowe Price': {
    name: 'T. Rowe Price',
    color: '#003DA5',
    logo: '/institution-logos/trowe.png',
  },
  'Ally Bank': {
    name: 'Ally Bank',
    color: '#8B4C9A',
    logo: '/institution-logos/ally.png',
  },
  'American Express': {
    name: 'American Express',
    color: '#006FCF',
    logo: '/institution-logos/amex.png',
  },
  'Capital One': {
    name: 'Capital One',
    color: '#004879',
    logo: '/institution-logos/capital-one.png',
  },
  'E*TRADE': {
    name: 'E*TRADE',
    color: '#6633CC',
    logo: '/institution-logos/etrade.png',
  },
  'Goldman Sachs': {
    name: 'Goldman Sachs',
    color: '#1E3A8A',
    logo: '/institution-logos/goldman.png',
  },
  Discover: {
    name: 'Discover',
    color: '#FF6000',
    logo: '/institution-logos/discover.png',
  },
  'Marcus by Goldman Sachs': {
    name: 'Marcus',
    color: '#1E3A8A',
    logo: '/institution-logos/marcus.png',
  },
  Coinbase: {
    name: 'Coinbase',
    color: '#0052FF',
    logo: '/institution-logos/coinbase.png',
  },
  Navient: {
    name: 'Navient',
    color: '#0066CC',
    logo: '/institution-logos/navient.png',
  },
  'Chase Auto Finance': {
    name: 'Chase Auto',
    color: '#117A65',
    logo: '/institution-logos/chase.png',
  },
  'Navy Federal': {
    name: 'Navy Federal',
    color: '#003F7F',
    logo: '/institution-logos/navy-federal.png',
  },
  'TD Ameritrade': {
    name: 'TD Ameritrade',
    color: '#00A651',
    logo: '/institution-logos/td-ameritrade.png',
  },
  USAA: { name: 'USAA', color: '#003F7F', logo: '/institution-logos/usaa.png' },
  'Chase Sapphire': {
    name: 'Chase Sapphire',
    color: '#117A65',
    logo: '/institution-logos/chase-sapphire.png',
  },
  Robinhood: {
    name: 'Robinhood',
    color: '#00C805',
    logo: '/institution-logos/robinhood.png',
  },
  WeBull: {
    name: 'WeBull',
    color: '#2962FF',
    logo: '/institution-logos/webull.png',
  },
  Chime: {
    name: 'Chime',
    color: '#0BBF6D',
    logo: '/institution-logos/chime.png',
  },
};

export const mockData = {
  accounts: [
    {
      id: 'acc_001',
      type: 'Checking',
      nickname: 'Main Account',
      balance: 12450.0,
      availableBalance: 11200.0,
      currency: 'USD',
    },
    {
      id: 'acc_002',
      type: 'Savings',
      nickname: 'Emergency Fund',
      balance: 25780.5,
      availableBalance: 25780.5,
      currency: 'USD',
    },
    {
      id: 'acc_003',
      type: 'Credit Card',
      nickname: 'Rewards Card',
      balance: -1245.3,
      availableBalance: 8754.7,
      currency: 'USD',
    },
    {
      id: 'acc_004',
      type: 'Investment',
      nickname: 'Portfolio',
      balance: 45600.25,
      availableBalance: 45600.25,
      currency: 'USD',
    },
    {
      id: 'acc_005',
      type: 'Checking',
      nickname: 'Chase Banking',
      balance: 8920.14,
      availableBalance: 8920.14,
      currency: 'USD',
    },
    {
      id: 'acc_006',
      type: 'Retirement',
      nickname: '401(k)',
      balance: 174250.67,
      availableBalance: 174250.67,
      currency: 'USD',
    },
    {
      id: 'acc_007',
      type: 'Retirement',
      nickname: 'Traditional IRA',
      balance: 62340.22,
      availableBalance: 62340.22,
      currency: 'USD',
    },
    {
      id: 'acc_008',
      type: 'Savings',
      nickname: '502A Health Savings',
      balance: 12450.11,
      availableBalance: 12450.11,
      currency: 'USD',
    },
    {
      id: 'acc_009',
      type: 'Education',
      nickname: 'College Savings 529',
      balance: 18230.89,
      availableBalance: 18230.89,
      currency: 'USD',
    },
    {
      id: 'acc_010',
      type: 'Savings',
      nickname: 'Disaster Savings',
      balance: 8500.0,
      availableBalance: 8500.0,
      currency: 'USD',
    },
  ] as Account[],

  transactions: [
    {
      id: 'txn_001',
      merchant: 'Whole Foods Market',
      category: { name: 'Groceries', color: '#34C759' },
      amount: -127.43,
      date: '2025-06-14T10:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_002',
      merchant: 'Apple Store',
      category: { name: 'Electronics', color: '#007AFF' },
      amount: -899.0,
      date: '2025-06-14T08:15:00Z',
      status: 'completed' as const,
      trackingNumber: '1Z999AA1234567890',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'In Transit' as const,
    },
    {
      id: 'txn_003',
      merchant: 'Amazon',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -156.78,
      date: '2025-06-14T12:45:00Z',
      status: 'completed' as const,
      trackingNumber: '771234567890',
      shippingProvider: 'FedEx' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_004',
      merchant: 'Salary Deposit',
      category: { name: 'Income', color: '#34C759' },
      amount: 3250.0,
      date: '2025-06-13T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_005',
      merchant: 'Best Buy',
      category: { name: 'Electronics', color: '#007AFF' },
      amount: -234.99,
      date: '2025-06-13T16:20:00Z',
      status: 'completed' as const,
      trackingNumber: '9400110200793123456789',
      shippingProvider: 'USPS' as const,
      deliveryStatus: 'Out for Delivery' as const,
    },
    {
      id: 'txn_006',
      merchant: 'Starbucks',
      category: { name: 'Coffee', color: '#FF9500' },
      amount: -6.85,
      date: '2025-06-13T07:45:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_007',
      merchant: 'Target',
      category: { name: 'Shopping', color: '#FF3B30' },
      amount: -89.42,
      date: '2025-06-12T14:30:00Z',
      status: 'completed' as const,
      trackingNumber: '1Z12345E0123456789',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_008',
      merchant: 'Gas Station',
      category: { name: 'Transportation', color: '#FF3B30' },
      amount: -45.2,
      date: '2025-06-12T18:30:00Z',
      status: 'pending' as const,
    },
    {
      id: 'txn_009',
      merchant: 'Netflix',
      category: { name: 'Entertainment', color: '#E50914' },
      amount: -15.99,
      date: '2025-06-11T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_010',
      merchant: 'Uber',
      category: { name: 'Transportation', color: '#000000' },
      amount: -23.45,
      date: '2025-06-11T18:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_011',
      merchant: 'Home Depot',
      category: { name: 'Home Improvement', color: '#FF8C00' },
      amount: -120.33,
      date: '2025-06-10T15:45:00Z',
      status: 'completed' as const,
      trackingNumber: '1ZHD123456789',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_012',
      merchant: 'Spotify',
      category: { name: 'Entertainment', color: '#1DB954' },
      amount: -9.99,
      date: '2025-06-10T05:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_031',
      merchant: 'Netflix',
      category: { name: 'Entertainment', color: '#E50914' },
      amount: -15.99,
      date: '2025-05-11T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_032',
      merchant: 'Spotify',
      category: { name: 'Entertainment', color: '#1DB954' },
      amount: -9.99,
      date: '2025-05-10T05:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_033',
      merchant: 'Adobe Creative Cloud',
      category: { name: 'Software', color: '#FF0000' },
      amount: -20.99,
      date: '2025-06-08T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_034',
      merchant: 'Adobe Creative Cloud',
      category: { name: 'Software', color: '#FF0000' },
      amount: -20.99,
      date: '2025-05-08T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_035',
      merchant: 'Adobe Creative Cloud',
      category: { name: 'Software', color: '#FF0000' },
      amount: -20.99,
      date: '2025-04-08T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_036',
      merchant: 'Planet Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -10.00,
      date: '2025-06-15T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_037',
      merchant: 'Planet Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -10.00,
      date: '2025-05-15T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_038',
      merchant: 'Planet Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -10.00,
      date: '2025-04-15T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_039',
      merchant: 'Amazon Prime',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -14.99,
      date: '2025-06-07T08:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_040',
      merchant: 'Amazon Prime',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -14.99,
      date: '2025-05-07T08:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_041',
      merchant: 'Disney+',
      category: { name: 'Entertainment', color: '#113CCF' },
      amount: -7.99,
      date: '2025-06-03T10:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_042',
      merchant: 'Disney+',
      category: { name: 'Entertainment', color: '#113CCF' },
      amount: -7.99,
      date: '2025-05-03T10:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_043',
      merchant: 'iCloud Storage',
      category: { name: 'Software', color: '#007AFF' },
      amount: -2.99,
      date: '2025-06-09T11:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_044',
      merchant: 'iCloud Storage',
      category: { name: 'Software', color: '#007AFF' },
      amount: -2.99,
      date: '2025-05-09T11:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_045',
      merchant: 'Hulu',
      category: { name: 'Entertainment', color: '#1CE783' },
      amount: -12.99,
      date: '2025-06-01T14:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_046',
      merchant: 'Hulu',
      category: { name: 'Entertainment', color: '#1CE783' },
      amount: -12.99,
      date: '2025-05-01T14:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_013',
      merchant: 'Walmart',
      category: { name: 'Groceries', color: '#34C759' },
      amount: -58.12,
      date: '2025-06-09T20:10:00Z',
      status: 'completed' as const,
      trackingNumber: 'WM123456789US',
      shippingProvider: 'USPS' as const,
      deliveryStatus: 'In Transit' as const,
    },
    {
      id: 'txn_014',
      merchant: "Lowe's",
      category: { name: 'Home Improvement', color: '#007AFF' },
      amount: -240.0,
      date: '2025-06-09T13:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_015',
      merchant: 'DoorDash',
      category: { name: 'Dining', color: '#FF3B30' },
      amount: -34.56,
      date: '2025-06-08T23:15:00Z',
      status: 'completed' as const,
      trackingNumber: 'DD123456',
      shippingProvider: 'FedEx' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_016',
      merchant: 'CVS Pharmacy',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -12.89,
      date: '2025-06-08T18:40:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_017',
      merchant: 'Lyft',
      category: { name: 'Transportation', color: '#FF00BF' },
      amount: -18.75,
      date: '2025-06-07T21:10:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_018',
      merchant: 'eBay',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -65.0,
      date: '2025-06-07T09:22:00Z',
      status: 'completed' as const,
      trackingNumber: 'EBAY987654321',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'Out for Delivery' as const,
    },
    {
      id: 'txn_019',
      merchant: 'Chipotle',
      category: { name: 'Dining', color: '#FF3B30' },
      amount: -11.25,
      date: '2025-06-06T13:37:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_020',
      merchant: 'Nike.com',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -120.0,
      date: '2025-06-06T16:05:00Z',
      status: 'completed' as const,
      trackingNumber: '1ZNIKE123456',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'In Transit' as const,
    },
    {
      id: 'txn_021',
      merchant: 'Paycheck',
      category: { name: 'Income', color: '#34C759' },
      amount: 3250.0,
      date: '2025-06-05T00:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_022',
      merchant: 'Costco',
      category: { name: 'Groceries', color: '#34C759' },
      amount: -210.45,
      date: '2025-06-05T19:40:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_023',
      merchant: 'Apple Music',
      category: { name: 'Entertainment', color: '#E50914' },
      amount: -10.99,
      date: '2025-06-04T04:20:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_047',
      merchant: 'Apple Music',
      category: { name: 'Entertainment', color: '#E50914' },
      amount: -10.99,
      date: '2025-05-04T04:20:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_048',
      merchant: 'Apple Music',
      category: { name: 'Entertainment', color: '#E50914' },
      amount: -10.99,
      date: '2025-04-04T04:20:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_024',
      merchant: 'Best Buy',
      category: { name: 'Electronics', color: '#007AFF' },
      amount: -79.99,
      date: '2025-06-04T17:55:00Z',
      status: 'completed' as const,
      trackingNumber: 'BB987654321',
      shippingProvider: 'FedEx' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_025',
      merchant: 'Grocery Store',
      category: { name: 'Groceries', color: '#34C759' },
      amount: -92.1,
      date: '2025-06-03T11:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_026',
      merchant: 'Amazon',
      category: { name: 'Shopping', color: '#FF9500' },
      amount: -32.45,
      date: '2025-06-03T14:05:00Z',
      status: 'completed' as const,
      trackingNumber: 'AMZ123987456',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'In Transit' as const,
    },
    {
      id: 'txn_027',
      merchant: 'Subway',
      category: { name: 'Dining', color: '#FF3B30' },
      amount: -8.9,
      date: '2025-06-02T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_028',
      merchant: 'Apple.com',
      category: { name: 'Electronics', color: '#007AFF' },
      amount: -299.0,
      date: '2025-06-02T07:30:00Z',
      status: 'completed' as const,
      trackingNumber: 'APL123456789',
      shippingProvider: 'UPS' as const,
      deliveryStatus: 'Out for Delivery' as const,
    },
    {
      id: 'txn_029',
      merchant: 'Gym Membership',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -55.0,
      date: '2025-06-01T02:30:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_030',
      merchant: 'Whole Foods Market',
      category: { name: 'Groceries', color: '#34C759' },
      amount: -140.25,
      date: '2025-06-01T18:15:00Z',
      status: 'completed' as const,
      trackingNumber: 'WF123456',
      shippingProvider: 'USPS' as const,
      deliveryStatus: 'Delivered' as const,
    },
    {
      id: 'txn_049',
      merchant: 'Verizon Wireless',
      category: { name: 'Utilities', color: '#CD212A' },
      amount: -89.99,
      date: '2025-06-15T08:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_050',
      merchant: 'Verizon Wireless',
      category: { name: 'Utilities', color: '#CD212A' },
      amount: -89.99,
      date: '2025-05-15T08:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_051',
      merchant: 'Verizon Wireless',
      category: { name: 'Utilities', color: '#CD212A' },
      amount: -89.99,
      date: '2025-04-15T08:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_052',
      merchant: 'Xfinity',
      category: { name: 'Utilities', color: '#7B68EE' },
      amount: -79.99,
      date: '2025-06-20T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_053',
      merchant: 'Xfinity',
      category: { name: 'Utilities', color: '#7B68EE' },
      amount: -79.99,
      date: '2025-05-20T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_054',
      merchant: 'Xfinity',
      category: { name: 'Utilities', color: '#7B68EE' },
      amount: -79.99,
      date: '2025-04-20T12:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_055',
      merchant: 'State Farm Insurance',
      category: { name: 'Insurance', color: '#DA020E' },
      amount: -156.34,
      date: '2025-06-01T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_056',
      merchant: 'State Farm Insurance',
      category: { name: 'Insurance', color: '#DA020E' },
      amount: -156.34,
      date: '2025-05-01T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_057',
      merchant: 'State Farm Insurance',
      category: { name: 'Insurance', color: '#DA020E' },
      amount: -156.34,
      date: '2025-04-01T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_058',
      merchant: 'Allstate Insurance',
      category: { name: 'Insurance', color: '#0033A0' },
      amount: -45.67,
      date: '2025-06-05T10:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_059',
      merchant: 'Allstate Insurance',
      category: { name: 'Insurance', color: '#0033A0' },
      amount: -45.67,
      date: '2025-05-05T10:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_060',
      merchant: 'Allstate Insurance',
      category: { name: 'Insurance', color: '#0033A0' },
      amount: -45.67,
      date: '2025-04-05T10:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_061',
      merchant: 'Blue Cross Blue Shield',
      category: { name: 'Insurance', color: '#004785' },
      amount: -234.56,
      date: '2025-06-01T07:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_062',
      merchant: 'Blue Cross Blue Shield',
      category: { name: 'Insurance', color: '#004785' },
      amount: -234.56,
      date: '2025-05-01T07:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_063',
      merchant: 'Blue Cross Blue Shield',
      category: { name: 'Insurance', color: '#004785' },
      amount: -234.56,
      date: '2025-04-01T07:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_064',
      merchant: 'Northwestern Mutual',
      category: { name: 'Insurance', color: '#8B4513' },
      amount: -67.89,
      date: '2025-06-10T11:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_065',
      merchant: 'Northwestern Mutual',
      category: { name: 'Insurance', color: '#8B4513' },
      amount: -67.89,
      date: '2025-05-10T11:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_066',
      merchant: 'Northwestern Mutual',
      category: { name: 'Insurance', color: '#8B4513' },
      amount: -67.89,
      date: '2025-04-10T11:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_067',
      merchant: 'PG&E Electric',
      category: { name: 'Utilities', color: '#FF6600' },
      amount: -123.45,
      date: '2025-06-08T14:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_068',
      merchant: 'PG&E Electric',
      category: { name: 'Utilities', color: '#FF6600' },
      amount: -134.52,
      date: '2025-05-08T14:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_069',
      merchant: 'PG&E Electric',
      category: { name: 'Utilities', color: '#FF6600' },
      amount: -98.76,
      date: '2025-04-08T14:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_070',
      merchant: 'SoCal Gas Company',
      category: { name: 'Utilities', color: '#1E90FF' },
      amount: -45.23,
      date: '2025-06-12T15:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_071',
      merchant: 'SoCal Gas Company',
      category: { name: 'Utilities', color: '#1E90FF' },
      amount: -52.67,
      date: '2025-05-12T15:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_072',
      merchant: 'SoCal Gas Company',
      category: { name: 'Utilities', color: '#1E90FF' },
      amount: -38.91,
      date: '2025-04-12T15:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_073',
      merchant: 'City Water Department',
      category: { name: 'Utilities', color: '#4682B4' },
      amount: -67.34,
      date: '2025-06-03T13:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_074',
      merchant: 'City Water Department',
      category: { name: 'Utilities', color: '#4682B4' },
      amount: -72.15,
      date: '2025-05-03T13:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_075',
      merchant: 'City Water Department',
      category: { name: 'Utilities', color: '#4682B4' },
      amount: -58.93,
      date: '2025-04-03T13:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_076',
      merchant: 'LA Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -39.99,
      date: '2025-06-18T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_077',
      merchant: 'LA Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -39.99,
      date: '2025-05-18T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_078',
      merchant: 'LA Fitness',
      category: { name: 'Health', color: '#8E44AD' },
      amount: -39.99,
      date: '2025-04-18T06:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_079',
      merchant: 'AT&T',
      category: { name: 'Utilities', color: '#00A8E1' },
      amount: -145.67,
      date: '2025-06-25T16:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_080',
      merchant: 'AT&T',
      category: { name: 'Utilities', color: '#00A8E1' },
      amount: -145.67,
      date: '2025-05-25T16:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_081',
      merchant: 'AT&T',
      category: { name: 'Utilities', color: '#00A8E1' },
      amount: -145.67,
      date: '2025-04-25T16:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_082',
      merchant: 'Microsoft 365',
      category: { name: 'Software', color: '#0078D4' },
      amount: -12.99,
      date: '2025-06-07T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_083',
      merchant: 'Microsoft 365',
      category: { name: 'Software', color: '#0078D4' },
      amount: -12.99,
      date: '2025-05-07T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_084',
      merchant: 'Microsoft 365',
      category: { name: 'Software', color: '#0078D4' },
      amount: -12.99,
      date: '2025-04-07T09:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_085',
      merchant: 'ADT Security',
      category: { name: 'Utilities', color: '#B22222' },
      amount: -54.99,
      date: '2025-06-14T17:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_086',
      merchant: 'ADT Security',
      category: { name: 'Utilities', color: '#B22222' },
      amount: -54.99,
      date: '2025-05-14T17:00:00Z',
      status: 'completed' as const,
    },
    {
      id: 'txn_087',
      merchant: 'ADT Security',
      category: { name: 'Utilities', color: '#B22222' },
      amount: -54.99,
      date: '2025-04-14T17:00:00Z',
      status: 'completed' as const,
    },
  ] as Transaction[],
};

// Helper function to generate AccountCardDTO from mock data
export const getCompactAccountCards = (): AccountCardDTO[] => {
  return mockAccountsEnhanced.map((account) =>
    accountToCardDTO(
      account,
      mockData.transactions.filter((t) => Math.random() > 0.7), // Random subset of transactions
      mockInstitutions[account.institutionName || 'Chase Bank']
    )
  );
};
